export const topics = [
  "Advanced TypeScript Patterns for Scalable Apps",
  "Kubernetes vs Docker Swarm: A 2026 Perspective",
  "Optimizing Next.js for Core Web Vitals",
  "The State of Serverless Architecture in 2026",
  "Implementing Zero Trust Security Models",
  "Rust for JavaScript Developers: Value Proposition",
  "Microservices vs Monolith: When to Break Up",
  "GraphQL Federation: managing a graph at scale",
  "Edge Computing: Logic closer to the user",
  "Automating Infrastructure with Terraform CDK",
  "WebAssembly: Beyond the Browser",
  "Database Sharding Strategies for High Traffic",
  "Event-Driven Architectures with Kafka and RabbitMQ",
  "Understanding CRDTs for Real-time Collaboration",
  "AI Agents in Production: Observability Challenges",
  "PostgreSQL Performance Tuning for Senior Devs",
  "React Server Components: Deep Dive",
  "Building Resilient APIs with Rate Limiting",
  "Chaos Engineering: Breaking things on purpose",
  "Modern CI/CD Pipelines with GitHub Actions",
  "Redis Caching Strategies for Microservices",
  "Green IT: Optimizing Cloud Carbon Footprint",
  "Accessibility in Modern SPAs: Beyond ARIA",
  "WebRTC for Real-time Communication scale",
  "Introduction to eBPF for Observability"
];
